project:
  type: website
  output-dir: "."

website:
  title: "About" 
  navbar:
    pinned: true
    left:
      - text: 'Class Projects'
        href: class_projects.qmd
      - text: 'Personal Projects'
        href: personal_blog.qmd
      - text: 'Class Blog Posts'
        href: class_blog.qmd
  page-footer: 
    center: "Powered with GitHub, Quarto and Rstudio<br>Â© Daniel Noone, 2023"

format:
  html:
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
